package ewgen

import java.time.Instant

import scala.annotation.tailrec

object Generator {

  case class GroupResult(
      group: Config.Group,
      probe: Clang.Probe
  )

  case class Output(headerText: String, sourceText: String)

  // XXX rewrite trailing `()` to `(void)` to silence -Wstrict-prototypes
  private val EmptyArgsTail = """\(\s*\)\s*;\s*$""".r

  def splitFnType(qualType: String): (String, String) = {
    @tailrec def loop(i: Int, depth: Int): Option[Int] =
      if (i >= qualType.length) None
      else
        qualType.charAt(i) match {
          case '(' if depth == 0 => Some(i)
          case '('               => loop(i + 1, depth + 1)
          case ')'               => loop(i + 1, depth - 1)
          case _                 => loop(i + 1, depth)
        }
    val idx  = loop(0, 0).getOrElse(sys.error(s"Cannot split function qualType: $qualType"))
    val ret  = qualType.substring(0, idx).trim
    val args = qualType.substring(idx).trim
    (ret, args)
  }

  private def fnTypedef(prefix: String, fn: Clang.FunctionDecl): String = {
    val raw = typedefFromSignature(prefix, fn.name, publicName(fn), fn.signature).getOrElse {
      val (ret, args) = splitFnType(fn.qualType)
      s"typedef $ret ${prefix}_${publicName(fn)}$args;"
    }
    val typedef = EmptyArgsTail.replaceAllIn(raw, "(void);")
    if (fn.docComment.trim.isEmpty) typedef else s"${fn.docComment}\n$typedef"
  }

  def typedefFromSignature(prefix: String, fnName: String, signature: String): Option[String] =
    typedefFromSignature(prefix, fnName, fnName, signature)

  def typedefFromSignature(
      prefix: String,
      fnName: String,
      publicName: String,
      signature: String
  ): Option[String] = {
    val clean = stripGnuAttributes(signature)
      .replaceAll("""(?m)^\s*__extension__\s+extern\s+""", "")
      .replaceAll("""(?m)^\s*extern\s+""", "")
      .stripSuffix(";")
      .trim
    val idx = findFunctionName(clean, fnName)
    if (idx < 0) None
    else {
      Some(s"typedef ${clean.substring(0, idx)}${prefix}_$publicName${clean.substring(idx + fnName.length)};")
    }
  }

  private def publicName(fn: Clang.FunctionDecl): String =
    fn.versionTag match {
      case Some(tag) => s"${fn.name}_$tag"
      case None      => fn.name
    }

  private def findFunctionName(signature: String, fnName: String): Int = {
    def isIdent(c: Char) = c.isLetterOrDigit || c == '_'
    @tailrec def loop(from: Int): Int = {
      val idx = signature.indexOf(fnName, from)
      if (idx < 0) -1
      else {
        val beforeOk = idx == 0 || !isIdent(signature.charAt(idx - 1))
        val after    = idx + fnName.length
        val afterOk  = after >= signature.length || !isIdent(signature.charAt(after))
        if (beforeOk && afterOk) idx else loop(idx + 1)
      }
    }
    loop(0)
  }

  private def stripGnuAttributes(s: String): String = {
    val marker = "__attribute__"
    def skipWhitespace(from: Int): Int =
      (from until s.length).find(i => !s.charAt(i).isWhitespace).getOrElse(s.length)
    @tailrec def skipParens(i: Int, depth: Int): Int =
      if (i >= s.length) i
      else
        s.charAt(i) match {
          case '('                   => skipParens(i + 1, depth + 1)
          case ')' if depth - 1 == 0 => i + 1
          case ')'                   => skipParens(i + 1, depth - 1)
          case _                     => skipParens(i + 1, depth)
        }
    Iterator
      .unfold(0) { i =>
        if (i >= s.length) None
        else if (s.startsWith(marker, i)) {
          val afterMarker = skipWhitespace(i + marker.length)
          val afterAttr =
            if (afterMarker < s.length && s.charAt(afterMarker) == '(') skipParens(afterMarker, 0)
            else afterMarker
          Some("" -> afterAttr)
        } else Some(s.charAt(i).toString -> (i + 1))
      }
      .mkString
  }

  private def banner(wrangler: Config.Wrangler, headers: Vector[String]): String = {
    val now = Instant.now().toString
    val lines = Vector(
      s"// AUTO-GENERATED by ewgen. DO NOT EDIT.",
      s"// wrangler: ${wrangler.name}",
      s"// generated: $now",
      s"// inputs:"
    ) ++ headers.map(h => s"//   $h")
    lines.mkString("\n")
  }

  def emit(wrangler: Config.Wrangler, results: Vector[GroupResult]): Output = {
    val allHeaders = results.flatMap(r => r.group.headers.map(h => s"${r.group.name}: $h"))
    Output(renderHeader(wrangler, results, allHeaders), renderSource(wrangler, results, allHeaders))
  }

  private def renderHeader(wrangler: Config.Wrangler, results: Vector[GroupResult], headers: Vector[String]): String = {
    val W = wrangler.name

    val macroSection = results.flatMap(r => r.probe.macros.map(m => s"#define ${m.raw}"))
    val typesSection = results.flatMap(_.probe.typeSlices)
    val typedefs = results.flatMap { r =>
      val prefix = s"${W}_${r.group.name}"
      r.probe.functions.map(fn => fnTypedef(prefix, fn))
    }
    val externs = results.flatMap { r =>
      val prefix = s"${W}_${r.group.name}"
      r.probe.functions.map(fn => s"extern ${prefix}_${publicName(fn)}* ${publicName(fn)};")
    }
    val resolveDecls = results.map { r =>
      s"void ${W}_${r.group.name}_resolve(${W}_lookup_t lookup, void* user);"
    }

    s"""#pragma once
       |
       |${banner(wrangler, headers)}
       |
       |#include <stddef.h>
       |#include <stdint.h>
       |#ifndef __cplusplus
       |#include <stdbool.h>
       |#endif
       |
       |#ifdef __cplusplus
       |#define _Bool bool
       |extern "C" {
       |#endif
       |
       |${macroSection.mkString("\n")}
       |
       |#if defined(__clang__) || defined(__GNUC__)
       |#pragma GCC diagnostic push
       |#pragma GCC diagnostic ignored "-Wgnu-anonymous-struct"
       |#pragma GCC diagnostic ignored "-Wnested-anon-types"
       |#endif
       |
       |${typesSection.mkString("\n\n")}
       |
       |#if defined(__clang__) || defined(__GNUC__)
       |#pragma GCC diagnostic pop
       |#endif
       |
       |${typedefs.mkString("\n")}
       |
       |${externs.mkString("\n")}
       |
       |typedef void* (*${W}_lookup_t)(void* user, const char* name);
       |${resolveDecls.mkString("\n")}
       |
       |#ifdef __cplusplus
       |}
       |#endif
       |""".stripMargin
  }

  private def renderSource(wrangler: Config.Wrangler, results: Vector[GroupResult], headers: Vector[String]): String = {
    val W = wrangler.name

    val defs = results.flatMap { r =>
      val prefix = s"${W}_${r.group.name}"
      r.probe.functions.map(fn => s"${prefix}_${publicName(fn)}* ${publicName(fn)};")
    }

    val resolveDefs = results.map { r =>
      val prefix = s"${W}_${r.group.name}"
      val body = r.probe.functions
        .map(fn => s"  ${publicName(fn)} = (${prefix}_${publicName(fn)}*) lookup(user, \"${fn.name}\");")
        .mkString("\n")
      s"""void ${W}_${r.group.name}_resolve(${W}_lookup_t lookup, void* user) {
         |$body
         |}""".stripMargin
    }

    s"""${banner(wrangler, headers)}
       |
       |#include "${W}.h"
       |
       |${defs.mkString("\n")}
       |
       |${resolveDefs.mkString("\n\n")}
       |""".stripMargin
  }
}
