set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR arm64)
set(CMAKE_OSX_ARCHITECTURES ${CMAKE_SYSTEM_PROCESSOR})

# XXX Use the project's bundled clang dist so the asan runtime matches what we shipped.
# Run `cmake -P build.cmake -DACTION=DIST` first to populate the dist dir.
set(_POLYREGION_BUILT_CLANG_DIR "${CMAKE_CURRENT_LIST_DIR}/../out/polyregion-Release-arm64-dylib-dist/bin")
if (NOT EXISTS "${_POLYREGION_BUILT_CLANG_DIR}/clang")
    message(FATAL_ERROR "asan toolchain expects a built polyregion clang at ${_POLYREGION_BUILT_CLANG_DIR}; build the dylib dist first")
endif ()

set(CMAKE_C_COMPILER "${_POLYREGION_BUILT_CLANG_DIR}/clang")
set(CMAKE_ASM_COMPILER "${_POLYREGION_BUILT_CLANG_DIR}/clang")
set(CMAKE_CXX_COMPILER "${_POLYREGION_BUILT_CLANG_DIR}/clang++")

find_program(CCACHE_PROGRAM ccache)
if (CCACHE_PROGRAM)
    set(CMAKE_C_COMPILER_LAUNCHER ${CCACHE_PROGRAM})
    set(CMAKE_CXX_COMPILER_LAUNCHER ${CCACHE_PROGRAM})
    set(CMAKE_ASM_COMPILER_LAUNCHER ${CCACHE_PROGRAM})
endif ()

set(CMAKE_C_COMPILER_TARGET ${CMAKE_SYSTEM_PROCESSOR}-apple-darwin)
set(CMAKE_ASM_COMPILER_TARGET ${CMAKE_SYSTEM_PROCESSOR}-apple-darwin)
set(CMAKE_CXX_COMPILER_TARGET ${CMAKE_SYSTEM_PROCESSOR}-apple-darwin)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)


set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_BUILD_TYPE release)
set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
set(VCPKG_OSX_ARCHITECTURES arm64)
set(VCPKG_MAKE_BUILD_TRIPLET "--host=${CMAKE_SYSTEM_PROCESSOR}-apple-darwin")
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${CMAKE_CURRENT_LIST_FILE}")
if (DEFINED ENV{CMAKE_SYSROOT})
    set(CMAKE_SYSROOT "$ENV{CMAKE_SYSROOT}")
endif ()

set(_SAN_BASE "-fsanitize=address,undefined -fno-sanitize=vptr")
set(_SAN_FLAGS_EXTRA "-mllvm -asan-globals=0")
set(_SAN_FLAGS "${_SAN_BASE} ${_SAN_FLAGS_EXTRA} -fno-omit-frame-pointer -g")
set(_SAN_LINK_FLAGS "${_SAN_BASE} -frtlib-add-rpath")
set(CMAKE_C_FLAGS_INIT "${CMAKE_C_FLAGS_INIT} ${_SAN_FLAGS}")
set(CMAKE_CXX_FLAGS_INIT "${CMAKE_CXX_FLAGS_INIT} ${_SAN_FLAGS}")
set(CMAKE_ASM_FLAGS_INIT "${CMAKE_ASM_FLAGS_INIT} ${_SAN_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${_SAN_LINK_FLAGS}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${_SAN_LINK_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${_SAN_LINK_FLAGS}")
