addSbtPlugin("com.timushev.sbt"          % "sbt-updates"  % "0.6.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.20")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly" % "1.1.0")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix" % "0.9.33")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt" % "2.4.5")
