addSbtPlugin("com.timushev.sbt"          % "sbt-updates"        % "0.6.2")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"       % "0.1.22")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"       % "1.2.0")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"       % "0.9.34")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"       % "2.4.6")
addSbtPlugin("com.lightbend.sbt"         % "sbt-java-formatter" % "0.7.0")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"            % "0.4.3")
