addSbtPlugin("com.timushev.sbt"          % "sbt-updates"        % "0.6.4")
// addSbtPlugin("org.typelevel"             % "sbt-tpolecat"     % "0.5.2")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"       % "2.3.0")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"       % "0.13.0")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"       % "2.5.2")
addSbtPlugin("com.lightbend.sbt"         % "sbt-java-formatter" % "0.8.0")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"            % "0.4.7")