addSbtPlugin("com.timushev.sbt"          % "sbt-updates"        % "0.6.4")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"       % "0.4.2")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"       % "2.1.0")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"       % "0.10.4")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"       % "2.5.0")
addSbtPlugin("com.lightbend.sbt"         % "sbt-java-formatter" % "0.8.0")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"            % "0.4.3")
