/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class polyregion_PolyregionCompiler */

#ifndef _Included_polyregion_PolyregionCompiler
#define _Included_polyregion_PolyregionCompiler
#ifdef __cplusplus
extern "C" {
#endif
#undef polyregion_PolyregionCompiler_BACKEND_1LLVM
#define polyregion_PolyregionCompiler_BACKEND_1LLVM 0L
/*
 * Class:      polyregion_PolyregionCompiler
 * Method:     compile
 * Signature:  ([BZS)Lpolyregion/Compilation;
 */
JNIEXPORT jobject JNICALL Java_polyregion_PolyregionCompiler_compile
  (JNIEnv *, jclass, jbyteArray, jboolean, jshort);

#ifdef __cplusplus
}
#endif
#endif
