/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class polyregion_PolyregionRuntime */

#ifndef _Included_polyregion_PolyregionRuntime
#define _Included_polyregion_PolyregionRuntime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:      polyregion_PolyregionRuntime
 * Method:     invoke
 * Signature:  ()Ljava/util/Optional;
 */
JNIEXPORT jobject JNICALL Java_polyregion_PolyregionRuntime_invoke
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
