file(STRINGS "${IDS_FILE}" _lines)
set(_out "")
set(_dist "")
if (DEFINED DIST_BIN AND DIST_BIN)
    set(_dist_bin "\${CMAKE_CURRENT_LIST_DIR}/../bin/${DIST_BIN}${EXE_SUFFIX}")
endif ()
set(_dist_env "")
if (DEFINED DIST_FILES_SUBDIR AND DIST_FILES_SUBDIR)
    set(_dist_env "POLYTEST_FILES_DIR=\${CMAKE_CURRENT_LIST_DIR}/../${DIST_FILES_SUBDIR};POLYTEST_PROFILE_DIR=\${CMAKE_CURRENT_LIST_DIR}/../test/profiles;POLYTEST_WORK_DIR=\${CMAKE_CURRENT_LIST_DIR}")
endif ()
foreach (_line IN LISTS _lines)
    if (_line STREQUAL "")
        continue()
    endif ()
    # Each line is "<id>" or "<id>\t<labels>" (tab-separated). Default any "offload-" id to device.
    string(REGEX MATCH "^([^\t]+)(\t(.*))?$" _ "${_line}")
    set(_id "${CMAKE_MATCH_1}")
    set(_id_labels "${CMAKE_MATCH_3}")
    set(_name "${NAME_PREFIX}-${_id}")
    set(_labels "")
    if (_id MATCHES "^offload-")
        set(_labels "device")
    endif ()
    if (_id_labels)
        if (_labels)
            set(_labels "${_labels};${_id_labels}")
        else ()
            set(_labels "${_id_labels}")
        endif ()
    endif ()
    if (DEFINED LABELS AND LABELS)
        if (_labels)
            set(_labels "${_labels};${LABELS}")
        else ()
            set(_labels "${LABELS}")
        endif ()
    endif ()

    string(APPEND _out "add_test(\"${_name}\" \"${BINARY}\" --run-task \"${_id}\")\n")
    # XXX harness exits 77 for "no compatible target"; let ctest count those as skipped, not failed
    set(_props " SKIP_RETURN_CODE 77")
    if (DEFINED WORKING_DIRECTORY AND WORKING_DIRECTORY)
        string(APPEND _props " WORKING_DIRECTORY \"${WORKING_DIRECTORY}\"")
    endif ()
    if (DEFINED ENVIRONMENT_MODIFICATION AND ENVIRONMENT_MODIFICATION)
        string(APPEND _props " ENVIRONMENT_MODIFICATION \"${ENVIRONMENT_MODIFICATION}\"")
    endif ()
    if (_labels)
        string(APPEND _props " LABELS \"${_labels}\"")
    endif ()
    if (_props)
        string(APPEND _out "set_tests_properties(\"${_name}\" PROPERTIES${_props})\n")
    endif ()

    if (_dist_bin)
        string(APPEND _dist "add_test(\"${_name}\" \"${_dist_bin}\" --run-task \"${_id}\")\n")
        set(_dist_props " SKIP_RETURN_CODE 77")
        if (_labels)
            string(APPEND _dist_props " LABELS \"${_labels}\"")
        endif ()
        if (_dist_env)
            string(APPEND _dist_props " ENVIRONMENT \"${_dist_env}\"")
        endif ()
        if (_dist_props)
            string(APPEND _dist "set_tests_properties(\"${_name}\" PROPERTIES${_dist_props})\n")
        endif ()
    endif ()
endforeach ()
file(WRITE "${TESTS_FILE}" "${_out}")
if (DEFINED DIST_TESTS_FILE AND DIST_TESTS_FILE)
    file(WRITE "${DIST_TESTS_FILE}" "${_dist}")
endif ()
