file(STRINGS "${IDS_FILE}" _ids)
set(_out "")
foreach (_id IN LISTS _ids)
    if (_id STREQUAL "")
        continue()
    endif ()
    set(_name "${NAME_PREFIX}-${_id}")
    string(APPEND _out "add_test(\"${_name}\" \"${BINARY}\" --run-task \"${_id}\")\n")
    set(_props "")
    if (DEFINED WORKING_DIRECTORY AND WORKING_DIRECTORY)
        string(APPEND _props " WORKING_DIRECTORY \"${WORKING_DIRECTORY}\"")
    endif ()
    set(_labels "")
    if (_id MATCHES "^offload-")
        set(_labels "device")
    endif ()
    if (DEFINED LABELS AND LABELS)
        if (_labels)
            set(_labels "${_labels};${LABELS}")
        else ()
            set(_labels "${LABELS}")
        endif ()
    endif ()
    if (_labels)
        string(APPEND _props " LABELS \"${_labels}\"")
    endif ()
    if (_props)
        string(APPEND _out "set_tests_properties(\"${_name}\" PROPERTIES${_props})\n")
    endif ()
endforeach ()
file(WRITE "${TESTS_FILE}" "${_out}")
