# Records a ctest entry into POLYREGION_TEST_DIST_ENTRIES so the test-dist install can emit a
# standalone CTestTestfile.cmake. COMMAND tokens prefixed with `:bin:<name>` resolve to the
# test-dist's bin/<name> at ctest invocation time via ${CMAKE_CURRENT_LIST_DIR}.
function(polyregion_test_dist_record)
    cmake_parse_arguments(ARG "" "NAME;WORKING_DIRECTORY;LABELS" "COMMAND;ENVIRONMENT" ${ARGN})
    if (NOT ARG_NAME OR NOT ARG_COMMAND)
        message(FATAL_ERROR "polyregion_test_dist_record requires NAME and COMMAND")
    endif ()
    set(_cmd "")
    foreach (_tok IN LISTS ARG_COMMAND)
        if (_tok MATCHES "^:bin:(.+)$")
            string(APPEND _cmd " \"\${CMAKE_CURRENT_LIST_DIR}/bin/${CMAKE_MATCH_1}${CMAKE_EXECUTABLE_SUFFIX}\"")
        else ()
            string(APPEND _cmd " \"${_tok}\"")
        endif ()
    endforeach ()
    set(_entry "add_test(${ARG_NAME}${_cmd})\n")
    set(_props "")
    if (ARG_WORKING_DIRECTORY)
        string(APPEND _props " WORKING_DIRECTORY \"${ARG_WORKING_DIRECTORY}\"")
    endif ()
    if (ARG_ENVIRONMENT)
        string(APPEND _props " ENVIRONMENT \"${ARG_ENVIRONMENT}\"")
    endif ()
    if (ARG_LABELS)
        string(APPEND _props " LABELS \"${ARG_LABELS}\"")
    endif ()
    if (_props)
        string(APPEND _entry "set_tests_properties(${ARG_NAME} PROPERTIES${_props})\n")
    endif ()
    set_property(GLOBAL APPEND_STRING PROPERTY POLYREGION_TEST_DIST_ENTRIES "${_entry}")
endfunction()
