file(STRINGS "${MANIFEST}" _lines)
set(CONST_DATA_BLOCKS "")
set(PROGRAM_ENTRIES "")
set(_first_entry TRUE)
foreach (_e IN LISTS _lines)
    if (NOT _e)
        continue()
    endif ()
    string(REPLACE "|" ";" _parts "${_e}")
    list(GET _parts 0 _arch)
    list(GET _parts 1 _suffix)
    list(GET _parts 2 _bin)
    file(READ "${_bin}" _hex HEX)
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _hex "${_hex}")
    set(_var "data_${PROGRAM_NAME}_${_suffix}_")
    string(REPLACE "-" "_" _var "${_var}")
    string(TOLOWER "${_var}" _var)
    string(APPEND CONST_DATA_BLOCKS "const static uint8_t ${_var}[] = {${_hex}};\n")
    if (NOT _first_entry)
        string(APPEND PROGRAM_ENTRIES ",\n")
    endif ()
    set(_first_entry FALSE)
    string(APPEND PROGRAM_ENTRIES "    {\"${_arch}\", std::vector(std::begin(${_var}), std::end(${_var}))}")
endforeach ()
configure_file("${TEMPLATE}" "${OUTPUT}" @ONLY)
