if (NOT BIN)
    message(FATAL_ERROR "BIN not set")
endif ()

set(RESOLVED_BIN "${BIN}")
if (WIN32 AND NOT EXISTS "${RESOLVED_BIN}")
    get_filename_component(BIN_DIR "${BIN}" DIRECTORY)
    get_filename_component(BIN_NAME "${BIN}" NAME)
    foreach (CFG IN ITEMS "${CONFIG}" "$ENV{CTEST_CONFIGURATION_TYPE}" Release RelWithDebInfo Debug MinSizeRel)
        if (CFG AND EXISTS "${BIN_DIR}/${CFG}/${BIN_NAME}")
            set(RESOLVED_BIN "${BIN_DIR}/${CFG}/${BIN_NAME}")
            break()
        endif ()
    endforeach ()
endif ()

if (NOT EXISTS "${RESOLVED_BIN}")
    message(FATAL_ERROR "Binary not found for dependency listing: ${BIN}")
endif ()

if (APPLE)
    execute_process(COMMAND otool -L "${RESOLVED_BIN}" OUTPUT_VARIABLE OUT RESULT_VARIABLE RC)
elseif (WIN32)
    execute_process(COMMAND dumpbin /DEPENDENTS "${RESOLVED_BIN}" OUTPUT_VARIABLE OUT RESULT_VARIABLE RC)
else ()
    execute_process(COMMAND ldd "${RESOLVED_BIN}" OUTPUT_VARIABLE OUT RESULT_VARIABLE RC)
endif ()
if (NOT RC EQUAL 0)
    message(FATAL_ERROR "Dependency listing failed for ${RESOLVED_BIN} (rc=${RC}):\n${OUT}")
endif ()
if (OUT MATCHES "(libLLVM|libMLIR|libclang-cpp|libpoly[^/]*\\.(so|dylib|dll))")
    message(FATAL_ERROR "Forbidden polyregion/llvm DSO in deps of ${RESOLVED_BIN}:\n${OUT}")
endif ()
message(STATUS "Deps OK: ${RESOLVED_BIN}")
