name: Linux

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    container:
      image: tom91136/centos7-llvm14:latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup env
        shell: bash
        run: cd /root; source /centos7-setup-llvm.sh env || true

      - name: Cache LLVM
        if: ${{ !env.ACT }}
        id: prepare-llvm
        uses: actions/cache@v2
        with:
          path: ./native/llvm
          key: ${{ runner.os }}-${{ hashFiles('./native/build_llvm.cmake') }}

      - name: Configure release build
        shell: bash
        working-directory: ./native
        run: ./build.sh configure .

      - name: Release build shim
        shell: bash
        working-directory: ./native
        run: ./build.sh build polyregion-shim-jvm

      - name: Release build runtime
        shell: bash
        working-directory: ./native
        run: ./build.sh build polyregion-runtime-jvm

      - name: Release build compiler
        shell: bash
        working-directory: ./native
        run: ./build.sh build polyregion-compiler-jvm

      - name: Check artefact
        shell: bash
        working-directory: ./native
        run: ls -lah build-linux-x86_64/bindings/jvm
