name: Linux

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    defaults:
      run:
        working-directory: ./native
    container:
      image: centos:7
    steps:

      - name: Cache compiler
        if: ${{ !env.ACT }}
        id: prepare-compilers
        uses: actions/cache@v2
        with:
          path: ~/
          key: ${{ runner.os }}-${{ hashFiles('./centos7-setup-llvm.sh') }}

      - name: Prepare build
        shell: bash
        run: cd; source ./centos7-setup-llvm.sh setup-build || true

      - name: Prepare compilers
        if: steps.prepare-compilers.outputs.cache-hit != 'true'
        shell: bash
        run: cd; source ./centos7-setup-llvm.sh setup-llvm || true

      - name: Configure release build
        shell: bash
        run: ./build.sh configure .

      - name: Release build shim
        shell: bash
        run: ./build.sh build polyregion-shim-jvm

      - name: Release build runtime
        shell: bash
        run: ./build.sh build polyregion-runtime-jvm

      - name: Release build compiler
        shell: bash
        run: ./build.sh build polyregion-compiler-jvm

      - name: Check artefact
        shell: bash
        run: file build-linux-x86_64/bindings/jvm/*
