name: Linux x86_64 build

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build:
    uses: ./.github/workflows/linux-shared.yaml
    secrets: inherit
    with:
      arch: x86_64
