name: Linux

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    container:
      image: tom91136/centos7-llvm14:latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup env
        shell: bash
        run: |
          cd /root; source /centos7-setup-llvm.sh setup-build || true
          cd /root; source /centos7-setup-llvm.sh env         || true
          echo "CXX=clang++" >> $GITHUB_ENV
          echo "CC=clang"    >> $GITHUB_ENV
          echo "LINKER=lld"  >> $GITHUB_ENV

      - name: Cache LLVM
        if: ${{ !env.ACT }}
        id: prepare-llvm
        uses: actions/cache@v3
        with:
          path: ./native/llvm
          key: ${{ runner.os }}-${{ hashFiles('./native/build_llvm.cmake') }}-${{ hashFiles('./native/ProjectConfig.cmake') }}

      - name: Configure release build
        shell: bash
        working-directory: ./native
        run: cmake -DCMAKE_BUILD_TYPE=Release -DACTION=CONFIGURE -P build.cmake

      - name: Release build shim
        shell: bash
        working-directory: ./native
        run: cmake -DCMAKE_BUILD_TYPE=Release -DACTION=BUILD -DTARGET=polyregion-shim-jvm -P build.cmake

      - name: Release build runtime
        shell: bash
        working-directory: ./native
        run: cmake -DCMAKE_BUILD_TYPE=Release -DACTION=BUILD -DTARGET=polyregion-runtime-jvm -P build.cmake

      - name: Release build compiler
        shell: bash
        working-directory: ./native
        run: cmake -DCMAKE_BUILD_TYPE=Release -DACTION=BUILD -DTARGET=polyregion-compiler-jvm -P build.cmake

      - name: Check artefact
        shell: bash
        working-directory: ./native
        run: ls -lah build-linux-x86_64/bindings/jvm
