name: Linux aarch64 build

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  release:
    uses: ./.github/workflows/linux-shared.yaml
    secrets: inherit
    with:
      build_arch: aarch64
      build_type: Release
