name: Linux build

on:
  workflow_call:
    inputs:
      build_sysroot_name:
        required: true
        type: string
      build_arch:
        required: true
        type: string
      build_type:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        # llvm-tblgen is in llvm
        run: |
          sudo apt-get install ninja-build llvm libcrypt-dev

      - name: Dotenv
        id: dotenv
        uses: falti/dotenv-action@v1.1
        with:
          path: ./native/.env

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: "${{ steps.dotenv.outputs.vcpkg_commit }}"

      - name: Check environment
        run: |
          clang --version
          llvm-tblgen --version
          echo "JAVA_HOME=$JAVA_HOME"
          echo "VCPKG_ROOT=$VCPKG_ROOT"

      - name: Restore sysroot cache
        if: ${{ !env.ACT }}
        id: restore-sysroot
        uses: actions/cache/restore@v4
        with:
          path: ./native/debian-sysroot-image-creator/out/sysroot-build/bullseye/debian_bullseye_${{ inputs.build_sysroot_name }}_sysroot.tar.xz
          key: ${{ runner.os }}-${{ inputs.build_arch }}-${{ hashFiles('./native/make_sysroot.py') }}

      - name: Build sysroot
        id: build-sysroot
        if: steps.restore-sysroot.outputs.cache-hit != 'true'
        working-directory: ./native
        run: ./make_sysroot.py build ${{ inputs.build_sysroot_name }}

      - name: Save sysroot cache
        if: steps.build-sysroot.outcome == 'success'
        uses: actions/cache/save@v4
        id: save-sysroot
        with:
          path: ./native/debian-sysroot-image-creator/out/sysroot-build/bullseye/debian_bullseye_${{ inputs.build_sysroot_name }}_sysroot.tar.xz
          key: ${{ runner.os }}-${{ inputs.build_arch }}-${{ hashFiles('./native/make_sysroot.py') }}

      - name: Prepare sysroot
        working-directory: ./native/debian-sysroot-image-creator
        run: |
          mkdir -p "sysroot_${{ inputs.build_sysroot_name }}"
          tar xf out/sysroot-build/bullseye/debian_bullseye_${{ inputs.build_sysroot_name }}_sysroot.tar.xz  -C ./sysroot_${{ inputs.build_sysroot_name }}
          echo "SYSROOT_PATH=$PWD/sysroot_${{ inputs.build_sysroot_name }}" >> $GITHUB_ENV

      - name: Restore LLVM cache
        if: ${{ !env.ACT }}
        id: restore-llvm
        uses: actions/cache/restore@v4
        with:
          path: ./native/llvm-*
          key: ${{ runner.os }}-${{ inputs.build_arch }}-${{ hashFiles('./native/build_llvm.cmake', './native/build_llvm_cache.cmake', './native/ProjectConfig.cmake', './native/toolchain*.cmake') }}

      - name: Build LLVM
        id: build-llvm
        if: steps.restore-llvm.outputs.cache-hit != 'true'
        working-directory: ./native
        run: cmake -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} -DARCH=${{ inputs.build_arch }} -DACTION=LLVM -DCMAKE_SYSROOT=${{ env.SYSROOT_PATH }} -P build.cmake

      - name: Save LLVM cache
        if: steps.build-llvm.outcome == 'success'
        uses: actions/cache/save@v4
        id: save-llvm
        with:
          path: ./native/llvm-*
          key: ${{ runner.os }}-${{ inputs.build_arch }}-${{ hashFiles('./native/build_llvm.cmake', './native/build_llvm_cache.cmake', './native/ProjectConfig.cmake', './native/toolchain*.cmake') }}

      - name: Configure release build
        working-directory: ./native
        run: cmake -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} -DARCH=${{ inputs.build_arch }} -DACTION=CONFIGURE -DCMAKE_SYSROOT=${{ env.SYSROOT_PATH }} -P build.cmake

      - name: Release build polycpp
        working-directory: ./native
        if: always()
        run: cmake -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} -DARCH=${{ inputs.build_arch }} -DACTION=BUILD -DTARGET=polycpp -P build.cmake

      - name: Release build polyrt-exec
        working-directory: ./native
        if: always()
        run: cmake -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} -DARCH=${{ inputs.build_arch }} -DACTION=BUILD -DTARGET=polyrt-exec -P build.cmake

      - name: Release build polyc-bin
        working-directory: ./native
        if: always()
        run: cmake -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} -DARCH=${{ inputs.build_arch }} -DACTION=BUILD -DTARGET=polyc-bin -P build.cmake

      - name: Release build JVM shim
        working-directory: ./native
        if: always()
        run: cmake -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} -DARCH=${{ inputs.build_arch }} -DACTION=BUILD -DTARGET=polyc-JNIshim -P build.cmake

      - name: Release build JVM runtime
        working-directory: ./native
        if: always()
        run: cmake -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} -DARCH=${{ inputs.build_arch }} -DACTION=BUILD -DTARGET=polyrt-JNI -P build.cmake

      - name: Release build JVM compiler
        working-directory: ./native
        if: always()
        run: cmake -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} -DARCH=${{ inputs.build_arch }} -DACTION=BUILD -DTARGET=polyc-JNI -P build.cmake

      - name: Check artefact
        working-directory: ./native
        if: always()
        run: |
          ls -lah build-linux-${{ inputs.build_arch }}/bindings/jvm
          ls -lah build-linux-${{ inputs.build_arch }}/polyc/
          ls -lah build-linux-${{ inputs.build_arch }}/polycpp/
          ls -lah build-linux-${{ inputs.build_arch }}/polyrt/
          show_libs () {
             for arg in $@; do
               file "$1"
               objdump -x "$1" | grep NEEDED
               echo "======"
             done
          }

          show_libs build-linux-${{ inputs.build_arch }}/bindings/jvm/*.so 
          show_libs build-linux-${{ inputs.build_arch }}/polyc/polyc
          show_libs build-linux-${{ inputs.build_arch }}/polycpp/polycpp
          show_libs build-linux-${{ inputs.build_arch }}/polyrt/polyrt-exec
