name: Linux i386 build

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  release:
    uses: ./.github/workflows/linux-shared.yaml
    secrets: inherit
    with:
      arch: i386
      type: Release
