name: macOS builds

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  arm64-release:
    uses: ./.github/workflows/macos-shared.yaml
    secrets: inherit
    with:
      build_arch: arm64
      build_type: Release
  x86_64-release:
    uses: ./.github/workflows/macos-shared.yaml
    secrets: inherit
    with:
      build_arch: x86_64
      build_type: Release
