name: macOS

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build:
    runs-on: macos-11.0

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install llvm cmake ninja
          echo "JAVA_HOME=${JAVA_HOME_8_X64}" >> "$GITHUB_ENV"
          echo "CXX=/usr/local/opt/llvm/bin/clang++" >> $GITHUB_ENV
          echo "CC=/usr/local/opt/llvm/bin/clang"    >> $GITHUB_ENV
          echo "LINKER=$(which ld)"                  >> $GITHUB_ENV

      - name: Cache LLVM
        if: ${{ !env.ACT }}
        id: prepare-llvm
        uses: actions/cache@v3
        with:
          path: ./native/llvm
          key: ${{ runner.os }}-${{ hashFiles('./native/build_llvm.cmake') }}-${{ hashFiles('./native/ProjectConfig.cmake') }}

      - name: Configure release build
        shell: bash
        working-directory: ./native
        run: cmake -DCMAKE_BUILD_TYPE=Release -DACTION=CONFIGURE -P build.cmake

      - name: Release build shim
        shell: bash
        working-directory: ./native
        run: cmake -DCMAKE_BUILD_TYPE=Release -DACTION=BUILD -DTARGET=polyregion-shim-jvm -P build.cmake

      - name: Release build runtime
        shell: bash
        working-directory: ./native
        run: cmake -DCMAKE_BUILD_TYPE=Release -DACTION=BUILD -DTARGET=polyregion-runtime-jvm -P build.cmake

      - name: Release build compiler
        shell: bash
        working-directory: ./native
        run: cmake -DCMAKE_BUILD_TYPE=Release -DACTION=BUILD -DTARGET=polyregion-compiler-jvm -P build.cmake

      - name: Check artefact
        shell: bash
        working-directory: ./native
        run: ls -lah build-darwin-x86_64/bindings/jvm
