name: Windows builds

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  AMD64-release:
    uses: ./.github/workflows/windows-shared.yaml
    secrets: inherit
    with:
      build_arch: AMD64
      build_type: Release
  X86-release:
    uses: ./.github/workflows/windows-shared.yaml
    secrets: inherit
    with:
      build_arch: X86
      build_type: release
