name: Windows

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache LLVM
        if: ${{ !env.ACT }}
        id: prepare-llvm
        uses: actions/cache@v3
        with:
          path: ./native/llvm
          key: ${{ runner.os }}-${{ hashFiles('./native/build_llvm.cmake') }}

      - name: Setup env
        working-directory: ./native
        shell: pwsh
        run: |
          echo "CXX=cl.exe"    | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          echo "CC=cl.exe"     | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          echo "LINKER=cl.exe" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

      - name: Configure release build
        working-directory: ./native
        run: cmake -DCMAKE_BUILD_TYPE=Release -DACTION=CONFIGURE -P build.cmake

      - name: Release build shim
        working-directory: ./native
        run: cmake -DCMAKE_BUILD_TYPE=Release -DACTION=BUILD -DTARGET=polyregion-shim-jvm -P build.cmake

      - name: Release build runtime
        working-directory: ./native
        run: cmake -DCMAKE_BUILD_TYPE=Release -DACTION=BUILD -DTARGET=polyregion-runtime-jvm -P build.cmake

      - name: Release build compiler
        working-directory: ./native
        run: cmake -DCMAKE_BUILD_TYPE=Release -DACTION=BUILD -DTARGET=polyregion-compiler-jvm -P build.cmake

      - name: Check artefact
        working-directory: ./native
        run: ls -lah build-windows-x86_64/bindings/jvm

 