name: Windows builds

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  AMD64-release:
    uses: ./.github/workflows/windows-shared.yaml
    secrets: inherit
    with:
      build_arch: amd64
      build_type: Release
      build_runs_on: windows-2025-vs2026
      check_runs_on: windows-2025-vs2026
      llvm_parallel_compile_jobs: "4"
      llvm_parallel_link_jobs: "2"
      flang_parallel_compile_jobs: "2"
  ARM64-release:
    uses: ./.github/workflows/windows-shared.yaml
    secrets: inherit
    with:
      build_arch: arm64
      build_type: Release
      build_runs_on: windows-11-arm
      check_runs_on: windows-11-arm
      llvm_parallel_compile_jobs: "4"
      llvm_parallel_link_jobs: "4"
      flang_parallel_compile_jobs: "2"
